### ISSUE TITLE
El TITLE de la página audioguías está en singular y sin acento (email nov 2015)

### ISSUE THREAD

**Issue by ineslaitano** [ineslaitano/rosarioturaccesible#12]

**Comment by nyuvone** [comment]
Hecho

**Comment by ineslaitano** [comment]
Falta ponerlo en plural, es decir, agregarle una S al final. Tiene que decir "Audioguías" porque son varias audioguías las que se presentan en esa página. Gracias

**Comment by nyuvone** [comment]
Hecho
Saludos, Nico 

    El Martes, 21 de febrero, 2017 10:36:35, ineslaitano <notifications@github.com> escribió:
 

 Falta ponerlo en plural, es decir, agregarle una S al final. Tiene que decir "Audioguías" porque son varias audioguías las que se presentan en esa página. Gracias—

**Comment by ineslaitano** [comment]
Ahora se cayó el sitio y no puedo testear
