### ISSUE TITLE
El TITLE de la sección "videos" no es correcto

### ISSUE THREAD

**Issue by ineslaitano** [ineslaitano/rosarioturaccesible#5]
Por ahora dice "videos - Rosario Turismo Accesible". Debería comenzar con mayúscula y llevar el título de la página, que por ahora es "Información en LSA" pero después puede cambiar.

**Comment by nyuvone** [comment]
Hecho

**Comment by ineslaitano** [comment]
¿pero quedó configurable desde el Admin como habíamos pedido?
gracias

**Comment by ineslaitano** [comment]
Ok pero tiene que ser configurable desde el Admin. Ver #1
